### PR TITLE
Fix critical bugs

### PR DESCRIPTION
**Pull request by szepeviktor**
### Description
Fixed the first batch of critical errors 🐛 

If you would like to find **the rest** please use PHPStan. I would gladly contribute.

### CODE REVIEW

**Comment by szepeviktor** [comment]
> [!NOTE]
> It goes like this: fixing docblocks reveals errors.

**Comment by seb86** [comment]
@szepeviktor I would appreciate it if you could apply PHPStan to each module which are on their own repository. This is just the packaging repository. Each repository are linked on the [issues selection](https://github.com/co-cart/co-cart/issues/new/choose).

**Comment by szepeviktor** [comment]
> This is just the packaging repository.

Please consider adding that info to https://github.com/co-cart/co-cart/blob/dev/.github/PULL_REQUEST_TEMPLATE.md

This is not really a PR but an inspiration for you.
I've included only the first few critical errors.

😲 viktor not a co-cart user

**Comment by szepeviktor** [comment]
`phpstan.neon`

```neon
# composer require php-stubs/woocommerce-stubs php-stubs/wp-cli-stubs szepeviktor/phpstan-wordpress --dev

includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    paths:
        - plugins/cocart/
        #- packages/admin/
        #- packages/compatibility/
        #- packages/products-api/
        #- packages/session-api/
        #- packages/third-party/
    excludePaths:
        - plugins/cocart/includes/cocart-deprecated-functions.php
    bootstrapFiles:
        - vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php
    scanFiles:
        - vendor/php-stubs/wp-cli-stubs/wp-cli-stubs.php
        - plugins/cocart/includes/cocart-deprecated-functions.php
        # For analyzing plugins/cocart/ only
        - packages/admin/includes/class-cocart-admin-notices.php
        - packages/products-api/includes/class-cocart-datetime.php
    level: 0
```

**Comment by seb86** [comment]
> > This is just the packaging repository.
> 
> Please consider adding that info to [`dev`/.github/PULL_REQUEST_TEMPLATE.md](https://github.com/co-cart/co-cart/blob/dev/.github/PULL_REQUEST_TEMPLATE.md?rgh-link-date=2023-08-04T16%3A05%3A41Z)
> 
> This is not really a PR but an inspiration for you. I've included only the first few critical errors.
> 
> 😲 viktor not a co-cart user

Yes updating contributing information on all repositories this weekend.

**Comment by szepeviktor** [comment]
🍇 I see the fruits of this PR.
Thank you!

**Pull request closed without merging**
